name: update-visidata
on:
  create:

jobs:
  update:
    # runs on version tag creation
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Send VisiData a Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: saulpw/visidata
          event-type: unzip-http
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
